server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.119.128:3306/admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: P@ssw0rd
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer
