server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer
